name: Run PowerShell Script

on:
  push:
    branches:
      - main  # or your working branch

jobs:
  run-vm-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up PowerShell
      uses: PowerShell/setup-powershell@v2
      with:
        pwsh-version: '7.5.1'  # Latest stable version

    - name: Run PowerShell script to create Azure VM
      run: pwsh ./VM.ps1
