name: Run PowerShell Script

on:
  push:
    branches:
      - main  # adjust as needed

jobs:
  run-vm-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install PowerShell
      uses: PowerShell/PowerShell@v1.2.0

    - name: Run PowerShell script to create Azure VM
      shell: pwsh
      run: ./VM.ps1
